<a href="https://colab.research.google.com/github/UdaySMukherjee/Machine-Learning-Tasks/blob/main/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Importing the dataset

In [ ]:
df = pd.read_csv("NB.csv")
df.head()

Document      Class
0         Havard is a great educational institution.  education
1            Educational greatness depends on ethics  education
2  A story of great ethics and educational greatness  education
3                  Rang De Basanti is a great cinema     cinema
4                   good movie depends on good story     cinema

# Data Preprocessing

In [ ]:
df.describe()

Document      Class
count                                            6          6
unique                                           6          2
top     Havard is a great educational institution.  education
freq                                             1          4

## Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_Class = LabelEncoder()
df['Activity'] = le_Class.fit_transform(df['Class'])
df.drop(['Class'], axis='columns', inplace=True)
df.head()

Document  Activity
0         Havard is a great educational institution.         1
1            Educational greatness depends on ethics         1
2  A story of great ethics and educational greatness         1
3                  Rang De Basanti is a great cinema         0
4                   good movie depends on good story         0

## Vectorizing the Document feature

In [ ]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['Document']).toarray()
y = df['Activity']
print(X)

[[0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 1 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 0 1 0]
 [0 1 1 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 2 0 0 0 0 0 1 0 1 0 1 0]
 [0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 1]]


## Splitting the dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the data using Sklearn Gaussian Naive Bayes Model

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
prediction = gnb.predict(X_test)

## Model Analysis

### Accuracy

In [ ]:
accuracy_score(y_test, prediction)

1.0

### F1 Score

In [ ]:
f1_score(y_test, prediction)

1.0

### Precision

In [ ]:
precision_score(y_test, prediction)

1.0

### Recall

In [ ]:
recall_score(y_test, prediction)

1.0